// Path: crates/commitment/src/tree/iavl/verifier.rs

use crate::primitives::hash::{HashCommitment, HashProof};
use crate::tree::iavl::proof::{self, IavlProof};
use ioi_types::app::Membership;
use ioi_types::error::ProofError;
use ioi_api::error::StateError;
use ioi_api::state::Verifier;
use parity_scale_codec::Decode;

/// A stateless verifier for proofs generated by an `IAVLTree` that uses a `HashCommitmentScheme`.
#[derive(Clone, Debug, Default)]
pub struct IAVLHashVerifier;

impl Verifier for IAVLHashVerifier {
    type Commitment = HashCommitment;
    type Proof = HashProof;

    fn commitment_from_bytes(&self, bytes: &[u8]) -> Result<Self::Commitment, StateError> {
        Ok(HashCommitment::new(bytes.to_vec()))
    }

    fn verify(
        &self,
        root: &Self::Commitment,
        proof_obj: &Self::Proof,
        key: &[u8],
        outcome: &Membership,
    ) -> Result<(), ProofError> {
        // The root commitment from an IAVLTree<HashCommitmentScheme> is the raw Merkle root hash.
        let root_hash: &[u8; 32] = root.as_ref().try_into().map_err(|_| {
            ProofError::InvalidExistence("Invalid root hash length. Expected 32 bytes.".into())
        })?;

        // The claimed value (or absence) being proven.
        let expected_value = match outcome {
            Membership::Present(v) => Some(v.as_slice()),
            Membership::Absent => None,
        };

        // For this tree implementation, the `HashProof`'s `value` field contains the
        // serialized `IavlProof` (either Existence or NonExistence).
        let proof_bytes = proof_obj.value();

        // Decode the inner IAVL proof from the SCALE-encoded bytes.
        let iavl_proof = IavlProof::decode(&mut &*proof_bytes)
            .map_err(|e| ProofError::Deserialization(e.to_string()))?;

        // Delegate to the canonical, stateless verification function.
        match proof::verify_iavl_proof(root_hash, key, expected_value, &iavl_proof) {
            Ok(true) => Ok(()),
            Ok(false) => Err(ProofError::RootMismatch),
            Err(e) => {
                log::warn!("[IAVLVerifier] Proof verification failed with error: {}", e);
                Err(e)
            }
        }
    }
}
